### ISSUE TITLE
doubts about the config.py

### ISSUE THREAD

**Issue by vicbp1** [AI-sandbox/XGMix#11]
Hi all, 
My doubts about the config.py file is about the generations flag. If I know that the admixture event between my target population was during the last 10 generations, do I have to reduce 
From:
generations = [0, 2, 4, 6, 8, 12, 16, 24, 32, 48] 
To:
generations = [0, 2, 4, 6, 8, 12]  or generations = [0, 2, 4, 6, 8, 12, 16] 

Or this parameter will not affect the inference?
One last doubt is how deep in time does xgmix can infer local ancestry? I mean 50 or more generations ago? (Considering that we have proxies for the admixture event)

Thank you in advance!

**Comment by weekend37** [comment]
Hey there! 
The short answer is that it's not *critical* in terms of performance.
However it does affect inference somewhat and if you're certain about your time since admixture, I would recommend changing it like you said!

This model is able to infer ancestries in very high generations including more than 50, yes. 
It obviously performs a bit worse than for the lower generation regime as the inference problem is getting harder but it still does quite well.
